<br /><br />
<div id="view-content">
	

<?php
	echo "<table style='padding:30px;'>";
	echo "<tr><th> ID: </th><th> Email: </th><th> Update </th><th> Ban User </th><th> Make Admin </th></tr> ";
	foreach ($this->users as $user){
	
	echo "<tr><td>".$user['id_user']."</td><td>".$user['username']."</td>";
	echo "<td><a class='btn btn-info' href='".$this->baseUrl()."/users/edit/id/".$user['id_user']."'> Edit </a></td>";
	echo "<td><a class='btn btn-danger' href='".$this->baseUrl()."/users/delete/id/".$user['id_user']."'> Ban User </a></td>";
	echo "<td><a class='btn btn-danger' href='".$this->baseUrl()."/users/delete/id/".$user['id_user']."'> Make Admin </a></td></tr>";

	}
	echo "</table>";

?>
</div>
