<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php echo $this->headLink(); ?>
</head>
<body>
   <div class="left-content">
	   <div class="inner-content">
		<!-- header-starts -->
			<div class="header-section">
			<!-- top_bg -->
			<div class="top_bg">
				
					<div class="header_top">
						<div class="top_right">
							
						</div>
						<div class="top_left">
							<!-- // Admin Notification Bar -->






										 <!-- Header Navbar -->
					        <nav class="navbar navbar-static-top" role="navigation">
					          <!-- Sidebar toggle button-->
					          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
					            <span class="sr-only">Toggle navigation</span>
					          </a>
					          <!-- Navbar Right Menu -->
					          <div class="navbar-custom-menu">
					            <ul class="nav navbar-nav">
					              <!-- Messages: style can be found in dropdown.less-->
					              <li class="dropdown messages-menu">
					                <!-- Menu toggle button -->
					                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
					                  <i class="fa fa-envelope-o"></i>
					                  <span class="label label-success">4</span>
					                </a>
					                <ul class="dropdown-menu">
					                  <li class="header">You have 4 messages</li>
					                  <li>
					                    <!-- inner menu: contains the messages -->
					                    <ul class="menu">
					                      <li><!-- start message -->
					                        <a href="#">
					                          <div class="pull-left">
					                            <!-- User Image -->
					                            <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
					                          </div>
					                          <!-- Message title and timestamp -->
					                          <h4>
					                            Support Team
					                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
					                          </h4>
					                          <!-- The message -->
					                          <p>Why not buy a new awesome theme?</p>
					                        </a>
					                      </li><!-- end message -->
					                    </ul><!-- /.menu -->
					                  </li>
					                  <li class="footer"><a href="#">See All Messages</a></li>
					                </ul>
					              </li><!-- /.messages-menu -->

					              <!-- Notifications Menu -->
					              <li class="dropdown notifications-menu">
					                <!-- Menu toggle button -->
					                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
					                  <i class="fa fa-bell-o"></i>
					                  <span class="label label-warning">10</span>
					                </a>
					                <ul class="dropdown-menu">
					                  <li class="header">You have 10 notifications</li>
					                  <li>
					                    <!-- Inner Menu: contains the notifications -->
					                    <ul class="menu">
					                      <li><!-- start notification -->
					                        <a href="#">
					                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
					                        </a>
					                      </li><!-- end notification -->
					                    </ul>
					                  </li>
					                  <li class="footer"><a href="#">View all</a></li>
					                </ul>
					              </li>
					              <!-- Tasks Menu -->
					              <li class="dropdown tasks-menu">
					                <!-- Menu Toggle Button -->
					                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
					                  <i class="fa fa-flag-o"></i>
					                  <span class="label label-danger">9</span>
					                </a>
					                <ul class="dropdown-menu">
					                  <li class="header">You have 9 tasks</li>
					                  <li>
					                    <!-- Inner menu: contains the tasks -->
					                    <ul class="menu">
					                      <li><!-- Task item -->
					                        <a href="#">
					                          <!-- Task title and progress text -->
					                          <h3>
					                            Design some buttons
					                            <small class="pull-right">20%</small>
					                          </h3>
					                          <!-- The progress bar -->
					                          <div class="progress xs">
					                            <!-- Change the css width attribute to simulate progress -->
					                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
					                              <span class="sr-only">20% Complete</span>
					                            </div>
					                          </div>
					                        </a>
					                      </li><!-- end task item -->
					                    </ul>
					                  </li>
					                  <li class="footer">
					                    <a href="#">View all tasks</a>
					                  </li>
					                </ul>
					              </li>
					              <!-- User Account Menu -->
					              <li class="dropdown user user-menu">
					                <!-- Menu Toggle Button -->
					                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
					                  <!-- The user image in the navbar-->
					                  <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
					                  <!-- hidden-xs hides the username on small devices so only the image appears. -->
					                  <span class="hidden-xs">Alexander Pierce</span>
					                </a>
					                <ul class="dropdown-menu">
					                  <!-- The user image in the menu -->
					                  <li class="user-header">
					                    <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
					                    <p>
					                      Alexander Pierce - Web Developer
					                      <small>Member since Nov. 2012</small>
					                    </p>
					                  </li>
					                  <!-- Menu Body -->
					                  <li class="user-body">
					                    <div class="col-xs-4 text-center">
					                      <a href="#">Followers</a>
					                    </div>
					                    <div class="col-xs-4 text-center">
					                      <a href="#">Sales</a>
					                    </div>
					                    <div class="col-xs-4 text-center">
					                      <a href="#">Friends</a>
					                    </div>
					                  </li>
					                  <!-- Menu Footer-->
					                  <li class="user-footer">
					                    <div class="pull-left">
					                      <a href="#" class="btn btn-default btn-flat">Profile</a>
					                    </div>
					                    <div class="pull-right">
					                      <a href="#" class="btn btn-default btn-flat">Sign out</a>
					                    </div>
					                  </li>
					                </ul>
					              </li>
					              <!-- Control Sidebar Toggle Button -->
					              <li>
					                <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
					              </li>
					            </ul>
					          </div>
					        </nav>










						</div>
							<div class="clearfix"> </div>
					</div>
				
					</div>
					<div class="clearfix"></div>
				<!-- /top_bg -->
				</div>
				<div class="header_bg">
						
							<div class="header">
								<div class="head-t">
									<div class="logo">
										<a href="index.html"><img src="images/logo.png" class="img-responsive" alt=""> </a>
									</div>
									
				
								</div>
							</div>
						</div>
				<!--content-->
			<div class="content">
				         
                <?php
                    // echo $this->content;
                    // echo $this->form;
                echo $this->layout()->content;
                ?>           
                            
			</div>
			<!--content-->
		</div>
</div>
				<!--//content-inner-->
			<!--/sidebar-menu-->
				<div class="sidebar-menu">
					<header class="logo1">
						<button class="sidebar-icon"> <span class="fa fa-bars"></span> </button> 
					</header>
						<div style="border-top:1px ridge rgba(255, 255, 255, 0.15)"></div>
                           <div class="menu">
									<ul id="menu" >

									













										<!-- // home for user -->

										<li><a href='<?php echo $this->baseUrl()."/cateogry/index"?>'><i class="fa fa-tachometer"></i> <span>Home</span></a></li>


										<!-- // Categories Actions -->

										 <li id="menu-academico" ><a href='#'><i class="fa fa-table"></i> <span> Categories</span> <span class="fa fa-angle-right" style="float: right"></span></a>
										 <!-- // All Courses -->
										   <ul id="menu-academico-sub" >

											<li id="menu-academico-avaliacoes" ><a href='<?php echo $this->baseUrl()."/cateogry/add"?>'><i class="lnr lnr-pencil"></i>New Category </a></li>


										  </ul>
										</li>

										<!-- // Courses Actions -->

										 <li id="menu-academico" ><a href='#'><i class="fa fa-table"></i> <span> Courses</span> <span class="fa fa-angle-right" style="float: right"></span></a>
										 <!-- // All Courses -->
										   <ul id="menu-academico-sub" >

											<li id="menu-academico-avaliacoes" ><a href='<?php echo $this->baseUrl()."/course/add"?>'> <i class="lnr lnr-pencil"></i> New Course </a></li>


										  </ul>
										</li>


										<!-- // User Requests  -->

										<li><a href='<?php echo $this->baseUrl()."/requests/index"?>'><i class="lnr lnr-envelope"></i> <span>Requests </span></a></li>


										<!-- // Website Statistics  -->

										<li><a href="#"><i class="lnr lnr-chart-bars"></i> <span>Statistics</span> <span class="fa fa-angle-right" style="float: right"></span></a>
										  <ul>
											<li><a href='<?php echo $this->baseUrl()."/admin/index"?>'><i class="lnr lnr-chart-bars"></i> No Of Users</a></li>
											<li><a href='<?php echo $this->baseUrl()."/course/index"?>'><i class="lnr lnr-chart-bars"></i>No Of Downloads</a></li>
											<li><a href='<?php echo $this->baseUrl()."/admin/count"?>'> <i class="lnr lnr-chart-bars"></i>No Of Requests</a></li>
										</ul>
										</li>

									
								  </ul>
								</div>
							  </div>
							  <div class="clearfix"></div>		
							</div>
							<script>
							var toggle = true;
										
							$(".sidebar-icon").click(function() {                
							  if (toggle)
							  {
								$(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
								$("#menu span").css({"position":"absolute"});
							  }
							  else
							  {
								$(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
								setTimeout(function() {
								  $("#menu span").css({"position":"relative"});
								}, 400);
							  }
											
											toggle = !toggle;
										});
							</script>
<!--js -->
<script src="js/jquery.nicescroll.js"></script>
<script src="js/scripts.js"></script>
<!-- Bootstrap Core JavaScript -->
   <script src="js/bootstrap.min.js"></script>
   <!-- /Bootstrap Core JavaScript -->
   <!-- real-time -->
<script language="javascript" type="text/javascript" src="js/jquery.flot.js"></script>
	<script type="text/javascript">

	$(function() {

		// We use an inline data source in the example, usually data would
		// be fetched from a server

		var data = [],
			totalPoints = 300;

		function getRandomData() {

			if (data.length > 0)
				data = data.slice(1);

			// Do a random walk

			while (data.length < totalPoints) {

				var prev = data.length > 0 ? data[data.length - 1] : 50,
					y = prev + Math.random() * 10 - 5;

				if (y < 0) {
					y = 0;
				} else if (y > 100) {
					y = 100;
				}

				data.push(y);
			}

			// Zip the generated y values with the x values

			var res = [];
			for (var i = 0; i < data.length; ++i) {
				res.push([i, data[i]])
			}

			return res;
		}

		// Set up the control widget

		var updateInterval = 30;
		$("#updateInterval").val(updateInterval).change(function () {
			var v = $(this).val();
			if (v && !isNaN(+v)) {
				updateInterval = +v;
				if (updateInterval < 1) {
					updateInterval = 1;
				} else if (updateInterval > 2000) {
					updateInterval = 2000;
				}
				$(this).val("" + updateInterval);
			}
		});

		var plot = $.plot("#placeholder", [ getRandomData() ], {
			series: {
				shadowSize: 0	// Drawing is faster without shadows
			},
			yaxis: {
				min: 0,
				max: 100
			},
			xaxis: {
				show: false
			}
		});

		function update() {

			plot.setData([getRandomData()]);

			// Since the axes don't change, we don't need to call plot.setupGrid()

			plot.draw();
			setTimeout(update, updateInterval);
		}

		update();

		// Add the Flot version string to the footer

		$("#footer").prepend("Flot " + $.plot.version + " &ndash; ");
	});

	</script>
<!-- /real-time -->
<script src="js/jquery.fn.gantt.js"></script>
    <script>

		$(function() {

			"use strict";

			$(".gantt").gantt({
				source: [{
					name: "Sprint 0",
					desc: "Analysis",
					values: [{
						from: "/Date(1320192000000)/",
						to: "/Date(1322401600000)/",
						label: "Requirement Gathering", 
						customClass: "ganttRed"
					}]
				},{
					name: " ",
					desc: "Scoping",
					values: [{
						from: "/Date(1322611200000)/",
						to: "/Date(1323302400000)/",
						label: "Scoping", 
						customClass: "ganttRed"
					}]
				},{
					name: "Sprint 1",
					desc: "Development",
					values: [{
						from: "/Date(1323802400000)/",
						to: "/Date(1325685200000)/",
						label: "Development", 
						customClass: "ganttGreen"
					}]
				},{
					name: " ",
					desc: "Showcasing",
					values: [{
						from: "/Date(1325685200000)/",
						to: "/Date(1325695200000)/",
						label: "Showcasing", 
						customClass: "ganttBlue"
					}]
				},{
					name: "Sprint 2",
					desc: "Development",
					values: [{
						from: "/Date(1326785200000)/",
						to: "/Date(1325785200000)/",
						label: "Development", 
						customClass: "ganttGreen"
					}]
				},{
					name: " ",
					desc: "Showcasing",
					values: [{
						from: "/Date(1328785200000)/",
						to: "/Date(1328905200000)/",
						label: "Showcasing", 
						customClass: "ganttBlue"
					}]
				},{
					name: "Release Stage",
					desc: "Training",
					values: [{
						from: "/Date(1330011200000)/",
						to: "/Date(1336611200000)/",
						label: "Training", 
						customClass: "ganttOrange"
					}]
				},{
					name: " ",
					desc: "Deployment",
					values: [{
						from: "/Date(1336611200000)/",
						to: "/Date(1338711200000)/",
						label: "Deployment", 
						customClass: "ganttOrange"
					}]
				},{
					name: " ",
					desc: "Warranty Period",
					values: [{
						from: "/Date(1336611200000)/",
						to: "/Date(1349711200000)/",
						label: "Warranty Period", 
						customClass: "ganttOrange"
					}]
				}],
				navigate: "scroll",
				scale: "weeks",
				maxScale: "months",
				minScale: "days",
				itemsPerPage: 10,
				onItemClick: function(data) {
					alert("Item clicked - show some details");
				},
				onAddClick: function(dt, rowId) {
					alert("Empty space clicked - add an item!");
				},
				onRender: function() {
					if (window.console && typeof console.log === "function") {
						console.log("chart rendered");
					}
				}
			});

			$(".gantt").popover({
				selector: ".bar",
				title: "I'm a popover",
				content: "And I'm the content of said popover.",
				trigger: "hover"
			});

			prettyPrint();

		});


</body>
</html>