


<div margin='auto' >
<?php
    
    echo "<h4><a href='".$this->baseUrl()."/course/mail'>Send mail</a></h4>";


    echo "<br /><label> Category Name : </label><h3>";
    echo $this->cateogry[0]['category']."<br>";
    echo "<br /><label> Category Image : </label><h3>";
    echo "<img src='".$this->baseUrl()."/images/category/".$this->cateogry[0]['image']."'/><br>";

    echo "<br /><label> Category Description : </label><h3>";
    echo $this->cateogry[0]['desc']."<br>";

    // var_dump($this->cateogry);
    
?>
</div>



<!-- <div class="content">
<div class="women_main"> -->
	<!-- start content -->
   <div class="w_content">
<!--        <div class="women">
            <div class="clearfix"></div>	
        </div>-->
        <!-- grids_of_4 -->
        <div class="grids_of_4">
            <?php
                foreach ($this->courses as $course){

                    echo '<div class="grid1_of_4">';
                    echo "<div class='content_box'>";

                    echo "<img src='".$this->baseUrl()."/images/courses/".$course['cours_image']."' class='img-responsive' alt=''></a>";


                    echo '<h4><a href='.$this->baseUrl()."/course/single/course_id/".$course['id_cours']."'>".$course['course'].'</a></h4>';

                    echo "<p> ".$course['cours_desc'] ."</p>";

                    echo '<div class="item_add"><span class="item_price"><a href ='.$this->baseUrl()."/course/single/course_id/".$course['id_cours'].'>Read More</a></span></div>';

                    echo '</div>';
                    echo ' </div>';
                    echo '</div>';
                }
            ?>
            <div class="clearfix"></div>
        </div>
	</div>
 <!--    </div>
</div>
		 -->	









