<?php
    foreach ($this->showmaterial as $tyimage){
      echo "<img src='".$this->baseUrl()."/images/materials/".$tyimage['mat_image']."'/>";
      echo "<br/><br/><lable>".$tyimage['desc_image']."</lable><br><br/>";
      ?>
      
      <div>
        <!-- Trigger/Open The Modal -->
        <button id="myBtn">Update</button>
        <!-- The Modal -->
        <div id="myModal" class="modal">
          <!-- Modal content -->
          <div class="modal-content">
            <span class="close">x</span>   
            <h1> Update Materials : </h>    
                <?php 
                    echo $this->form;
                ?>
          </div>
        </div>
    </div>
    <hr/>

     <?php
       
      echo "<br/><br/><a href='".$this->baseUrl()."/materials/downloadimage/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$tyimage['id_mat']."'><button>Download</button> </a> <br/><br/>";
    }



?>

                            
                            
                            
                            
                            
                            
                            




<script>
    // Get the modal
var modal = document.getElementById('myModal');

// Get the button that opens the modal
var btn = document.getElementById("myBtn");

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on the button, open the modal 
btn.onclick = function() {
    modal.style.display = "block";
}

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
    modal.style.display = "none";
}



</script>

                            