<?php
    foreach ($this->showmaterial as $tyimage){
      echo "<img src='".$this->baseUrl()."/images/materials/".$tyimage['mat_image']."'/>";
      echo "<br/><br/><lable>".$tyimage['desc_image']."</lable><br><br/>";
      ?>

      <?php
    echo "<a href='".$this->baseUrl()."/materials/editmaterial/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$tyimage['id_mat']."'><button>Updata Materials</button><br><hr/>";
    

    
      echo "<br/><br/><a href='".$this->baseUrl()."/materials/downloadimage/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$tyimage['id_mat']."'><button>Download</button> </a> <br/><br/>";
    }
    ?>
<h1>Add Comment</h1>

    <?php 

  echo $this->form;
?>
</div>
<hr/>




                            
